[versions]
agp = "8.5.2"
kotlin = "2.0.20"
coroutines = "1.8.1"
junit = "4.13.2"
mockk = "1.13.12"
sunmiPrinter = "1.0.23"
sunmiNfc = "2.3.1"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
sunmi-printer = { module = "com.sunmi:printerlibrary", version.ref = "sunmiPrinter" }
sunmi-nfc = { module = "com.sunmi:nfclibrary", version.ref = "sunmiNfc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
