<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tarifacao.Domain\Tarifacao.Domain.csproj" />
    <ProjectReference Include="..\Tarifacao.Contracts\Tarifacao.Contracts.csproj" />
  </ItemGroup>
</Project>
