<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pagamentos.Domain\Pagamentos.Domain.csproj" />
    <ProjectReference Include="..\Pagamentos.Contracts\Pagamentos.Contracts.csproj" />
  </ItemGroup>
</Project>
